# Generated by Django 3.0.10 on 2021-01-05 18:31

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('editor', '0004_richtextpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamFieldPage',
            fields=[
                ('page_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField(
                    [('image',
                      wagtail.core.blocks.StructBlock(
                          [('heading',
                            wagtail.core.blocks.CharBlock(
                                form_classname='full title')),
                           ('body',
                            wagtail.core.blocks.RichTextBlock()),
                           ('image',
                            wagtail.images.blocks.ImageChooserBlock())])),
                     ('document',
                      wagtail.core.blocks.StructBlock(
                          [('heading',
                            wagtail.core.blocks.CharBlock(
                                form_classname='full title')),
                           ('body',
                            wagtail.core.blocks.RichTextBlock()),
                           ('document',
                            wagtail.documents.blocks.DocumentChooserBlock(
                                icon='doc-full-inverse'))],
                          icon='doc-full-inverse')),
                     ('embed',
                      wagtail.core.blocks.StructBlock(
                          [('heading',
                            wagtail.core.blocks.CharBlock(
                                form_classname='full title')),
                           ('body',
                            wagtail.core.blocks.RichTextBlock()),
                           ('embed',
                            wagtail.embeds.blocks.EmbedBlock(
                                icon='media'))],
                          icon='media'))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
