# Generated by Django 3.0.10 on 2021-01-19 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('editor', '0007_streamfield_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EADObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('RCIN',
                 models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EADObjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('slug',
                 models.CharField(blank=True, max_length=128, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ead_objects',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='editor.EADObject')),
            ],
        ),
    ]
