# Generated by Django 3.0.10 on 2021-01-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_eadobject_eadobjectgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eadobjectgroup',
            name='ead_objects',
        ),
        migrations.AddField(
            model_name='eadobject',
            name='ead_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.EADObjectGroup'),
        ),
    ]
