# Generated by Django 3.0.10 on 2021-01-19 11:54

from django.db import migrations


def add_ead_objectgroups(apps, schema_editor):
    """ Default Themes from partner spreadsheet """
    EADObjectGroup = apps.get_model('editor', 'EADObjectGroup')
    EADObject = apps.get_model('editor', 'EADObject')
    shakespeare, created = EADObjectGroup.objects.get_or_create(
        title='William Shakespeare',
        slug='group_william_shakespeare',
        introduction='',
        description='',
    )
    EADObject.objects.get_or_create(
        RCIN="661421",
        ead_group=shakespeare
    )
    EADObject.objects.get_or_create(
        RCIN="40497",
        ead_group=shakespeare
    )
    EADObject.objects.get_or_create(
        RCIN="406072",
        ead_group=shakespeare
    )
    EADObject.objects.get_or_create(
        RCIN="447173.a",
        ead_group=shakespeare
    )

    on_the_stage, created = EADObjectGroup.objects.get_or_create(
        title='On the Stage',
        slug='group_stage',
        introduction='',
        description='',
    )
    EADObject.objects.get_or_create(
        RCIN="913000",
        ead_group=on_the_stage
    )
    EADObject.objects.get_or_create(
        RCIN="655013",
        ead_group=on_the_stage
    )
    EADObject.objects.get_or_create(
        RCIN="2913567",
        ead_group=on_the_stage
    )
    EADObject.objects.get_or_create(
        RCIN="GEO/MAIN/55462",
        ead_group=on_the_stage
    )

    on_the_page, created = EADObjectGroup.objects.get_or_create(
        title='On the Page',
        slug='group_page',
        introduction='',
        description='',
    )

    page_RCIN = ["1059072", "813725", "1008125", "MED/16/1/6"]
    for rcin in page_RCIN:
        EADObject.objects.get_or_create(
            RCIN=rcin,
            ead_group=on_the_page
        )


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_ead_group'),
    ]

    operations = [
        migrations.RunPython(add_ead_objectgroups)
    ]
