# Generated by Django 3.0.10 on 2021-02-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0001_initial'),
        ('editor', '0011_rename_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='ead_objects',
            field=models.ManyToManyField(related_name='themes', to='ead.EAD'),
        ),
        migrations.DeleteModel(
            name='ThemeObject',
        ),
    ]
