# Generated by Django 3.0.10 on 2021-02-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0012_theme_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='introduction',
        ),
    ]
