# Generated by Django 3.0.10 on 2021-03-01 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0022_storyobject_ead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyobjectcollection',
            name='story_objects',
        ),
        migrations.AddField(
            model_name='storyobject',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_objects', to='editor.StoryObjectCollection'),
        ),
    ]
