# Generated by Django 3.0.10 on 2021-03-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0023_story_objects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themeobjectcollection',
            old_name='theme_objects',
            new_name='ead_objects',
        ),
    ]
