# Generated by Django 3.0.10 on 2021-03-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0001_initial'),
        ('editor', '0024_ead_objects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themeobjectcollection',
            name='ead_objects',
        ),
        migrations.AddField(
            model_name='themeobjectcollection',
            name='ead_objects',
            field=models.ManyToManyField(related_name='themes', to='ead.EAD'),
        ),
    ]
