# Generated by Django 3.0.10 on 2021-06-08 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0035_ead_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="themeobjectcollection",
            name="ead_snippet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="theme_object_collection",
                to="editor.WagtailEADSnippet",
            ),
        ),
        migrations.AlterField(
            model_name="storyobject",
            name="ead_snippet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_snippet",
                to="editor.WagtailEADSnippet",
            ),
        ),
    ]
