# Generated by Django 3.0.10 on 2021-06-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0038_theme_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagtaileadsnippet',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
