# Generated by Django 3.0.10 on 2021-07-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0041_themeobject_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharciiif',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
