# Generated by Django 3.0.10 on 2020-12-11 16:08

from django.db import migrations, models
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharcTimelineEventSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=256)),
                ('start_date_year', models.IntegerField(default=0)),
                ('start_date_month', models.IntegerField(default=0)),
                ('start_date_day', models.IntegerField(default=0)),
                ('end_date_year', models.IntegerField(default=0)),
                ('end_date_month', models.IntegerField(default=0)),
                ('end_date_day', models.IntegerField(default=0)),
                ('headline', models.TextField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
                ('RCIN', models.TextField(blank=True, null=True)),
                ('creator', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
