# Generated by Django 3.0.10 on 2020-12-14 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharctimelineeventsnippet',
            options={
                'verbose_name': 'Timeline event',
                'verbose_name_plural': 'Timeline events'
            },
        ),
    ]
