# Generated by Django 3.0.10 on 2020-12-17 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('editor', '0002_timeline_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharctimelineeventsnippet',
            options={'ordering': ['start_date_year'],
                     'verbose_name': 'Timeline event',
                     'verbose_name_plural': 'Timeline events'},
        ),
    ]
