# Generated by Django 3.0.10 on 2021-01-06 12:32

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_streamfieldpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamfieldpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('image', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('body', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])), ('document', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('body', wagtail.core.blocks.RichTextBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse'))], icon='doc-full-inverse')), ('embed', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('body', wagtail.core.blocks.RichTextBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media'))], icon='media'))]),
        ),
    ]
