# Generated by Django 3.0.10 on 2021-01-14 15:15

from django.db import migrations
import autharch_sharc.editor.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_streamfield_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamfieldpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', autharch_sharc.editor.models.ResourceImageBlock()), ('page', autharch_sharc.editor.models.ResourcePageBlock()), ('document', autharch_sharc.editor.models.ResourceDocumentBlock(icon='doc-full-inverse')), ('embed', autharch_sharc.editor.models.ResourceEmbedBlock(icon='media'))]),
        ),
    ]
