# Generated by Django 3.0.10 on 2021-02-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_ead_group_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EADObjectGroup',
            new_name='Theme',
        ),
        migrations.RenameModel(
            old_name='EADObject',
            new_name='ThemeObject',
        ),
    ]
