# Generated by Django 3.0.10 on 2021-02-25 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0001_initial'),
        ('editor', '0017_auto_20210224_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='ead_objects',
        ),
        migrations.CreateModel(
            name='ThemeObjectCollection',
            fields=[
                ('streamfieldpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='editor.StreamFieldPage')),
                ('ead_objects', models.ManyToManyField(related_name='editor_themeobjectcollection_related', related_query_name='editor_themeobjectcollections', to='ead.EAD')),
            ],
            options={
                'abstract': False,
            },
            bases=('editor.streamfieldpage', models.Model),
        ),
        migrations.CreateModel(
            name='StoryObjectCollection',
            fields=[
                ('streamfieldpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='editor.StreamFieldPage')),
                ('ead_objects', models.ManyToManyField(related_name='editor_storyobjectcollection_related', related_query_name='editor_storyobjectcollections', to='ead.EAD')),
            ],
            options={
                'abstract': False,
            },
            bases=('editor.streamfieldpage', models.Model),
        ),
    ]
