# Generated by Django 3.0.10 on 2021-02-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0018_object_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
