# Generated by Django 3.0.10 on 2021-02-26 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0001_initial'),
        ('editor', '0019_delete_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryObjectCollectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='storyobjectcollection',
            name='ead_objects',
        ),
        migrations.RemoveField(
            model_name='themeobjectcollection',
            name='ead_objects',
        ),
        migrations.AddField(
            model_name='themeobjectcollection',
            name='theme_objects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='ead.EAD'),
        ),
        migrations.CreateModel(
            name='StoryObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.StoryObjectCollectionType')),
            ],
        ),
        migrations.AddField(
            model_name='storyobjectcollection',
            name='story_objects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story', to='editor.StoryObject'),
        ),
    ]
