# Generated by Django 3.0.10 on 2021-03-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0029_heading_richtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharcIIIF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iiif_uri', models.CharField(blank=True, max_length=512, null=True)),
                ('rcin', models.CharField(blank=True, max_length=256, null=True)),
                ('images_available', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
