# Generated by Django 3.0.10 on 2021-06-08 11:04

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0037_story_parental"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="themeobjectcollection",
            name="ead_snippet",
        ),
        migrations.CreateModel(
            name="ThemeObject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ead_snippet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_snippet",
                        to="editor.WagtailEADSnippet",
                    ),
                ),
                (
                    "theme",
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="theme_objects",
                        to="editor.ThemeObjectCollection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme object",
                "verbose_name_plural": "Theme objects",
            },
        ),
    ]
