# Generated by Django 3.0.10 on 2021-06-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0040_storyobject_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeobject',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
