# Generated by Django 3.0.10 on 2022-03-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0042_sharciiif_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sharciiif",
            options={
                "ordering": ["order"],
                "verbose_name": "IIF Uri",
                "verbose_name_plural": "IIF Uris",
            },
        ),
        migrations.AlterField(
            model_name="storyobject",
            name="connection_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="editor.StoryObjectCollectionType",
            ),
        ),
    ]
