# Generated by Django 3.0.10 on 2022-04-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0043_storyobject_connectiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedMaterialParsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcin', models.CharField(blank=True, max_length=256, null=True)),
                ('parsed', models.BooleanField(default=False)),
            ],
        ),
    ]
