# Generated by Django 3.0.10 on 2022-04-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0044_relatedmaterialparsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedmaterialparsed',
            name='related_material_parsed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
