# Generated by Django 3.0.10 on 2020-12-11 10:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEventWithImageSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=256)),
                ('start_date_year', models.IntegerField(default=0)),
                ('start_date_month', models.IntegerField(default=0)),
                ('start_date_day', models.IntegerField(default=0)),
                ('end_date_year', models.IntegerField(default=0)),
                ('end_date_month', models.IntegerField(default=0)),
                ('end_date_day', models.IntegerField(default=0)),
                ('headline', models.TextField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='TimelinePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TimelineSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=256)),
                ('start_date_year', models.IntegerField(default=0)),
                ('start_date_month', models.IntegerField(default=0)),
                ('start_date_day', models.IntegerField(default=0)),
                ('end_date_year', models.IntegerField(default=0)),
                ('end_date_month', models.IntegerField(default=0)),
                ('end_date_day', models.IntegerField(default=0)),
                ('headline', models.TextField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineSlideWithImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=256)),
                ('start_date_year', models.IntegerField(default=0)),
                ('start_date_month', models.IntegerField(default=0)),
                ('start_date_day', models.IntegerField(default=0)),
                ('end_date_year', models.IntegerField(default=0)),
                ('end_date_month', models.IntegerField(default=0)),
                ('end_date_day', models.IntegerField(default=0)),
                ('headline', models.TextField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineEventWithImageItem',
            fields=[
                ('timelineeventwithimagesnippet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_kdl_timeline.TimelineEventWithImageSnippet')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_events', to='django_kdl_timeline.TimelinePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('django_kdl_timeline.timelineeventwithimagesnippet', models.Model),
        ),
    ]
